### ISSUE TITLE
Cannot read property 'gltfLoader' of undefined

### ISSUE THREAD

**Issue by SongBana** [deepkolos/three-platformize-demo-taobao#1]
淘宝IDE 跑 demo后，报了这个错，请问下什么原因

**Comment by SongBana** [comment]
pages.json文件中需要添加
"window": {
    "defaultTitle": "My App",
     "enableSkia":"true"  
  }
添加后不报错了，但是直接闪退了。。

**Comment by deepkolos** [comment]
已经修复了，其实不加"enableSkia":"true"也能跑，官方的demo就是，不过npm发包估计有延迟
