### ISSUE TITLE
模拟器可以了，真机报错

### ISSUE THREAD

**Issue by SongBana** [deepkolos/three-platformize-demo-taobao#2]
刚开始是my.createCanvas is not a function
因为之前我们有过three.js的开发经验，用了 my._createCanvas后报了以下的错误
["Ku.__createCanvas is not a function", "", 0, 0, TypeError: Ku.__createCanvas is not a function

**Comment by deepkolos** [comment]
对的，淘宝小程序和微信小程序均不支持真机调试，只能预览

现在淘宝小程序真机很多问题
